# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clear_empty_attributes}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brandon Keepers"]
  s.date = %q{2009-11-13}
  s.description = %q{Save empty strings as nil to avoid lots of problems}
  s.email = %q{brandon@opensoul.org}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "clear_empty_attributes.gemspec",
     "init.rb",
     "lib/clear_empty_attributes.rb",
     "spec/clear_empty_attributes_spec.rb",
     "spec/setup_test_model.rb",
     "spec/spec_helper.rb",
     "tasks/clear_empty_attributes.rake"
  ]
  s.homepage = %q{http://github.com/grosser/clear_empty_attributes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Save empty strings as nil to avoid lots of problems}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/clear_empty_attributes_spec.rb",
     "spec/setup_test_model.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

